name: Build and deploy Bicep config

on:
  push:
    branches: [ main ]

permissions:
   id-token: write
   contents: read

env:
  RESOURCE_GROUP: "aks-maffe-maandag"
  DNS_PREFIX: "aksMaffeMaandag"

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Builds and pushes an image up to your Azure Container Registry
      - name: Deploy Bicep config
        run: |
          az deployment group create --resource-group ${{ env.RESOURCE_GROUP }} --template-uri https://raw.githubusercontent.com/aristosvo/aks-maffe-maandag/main/main.json -p dnsPrefix=${{ env.DNS_PREFIX }}


